# Basic Site Settings
locale                   : "en-US"
title                    : "lindseynield"
name                     : &name "Lindsey Nield"
user_description         : "Mission-driven machine learning engineer and Python developer with 4+ years of experience building end-to-end ML pipelines and data infrastructures. My skills and interests lie at the intersection of software development, machine learning, data engineering, and cloud development to unlock content and deliver insights from imagery and geospatial datasets. Seeking opportunities to work cross-functionally to design and build novel AI/ML solutions to geospatial problems. "
url                      : https://lindseynield.github.io 
baseurl                  : ""
repository               : "lindseynield/lindseynield.github.io"

# User settings
username: "lindseynield"
greeting: "Hi, I'm Lindsey 👋"
user_title: Machine Learning & Data Engineer 
email: lindsey.g.nield@gmail.com
github_username:  lindseynield
linkedin_username: lindseynield

# Google-analytics
google-analytics:
  id: ""

markdown: kramdown