# Basic Site Settings
locale                   : "en-US"
title                    : "lindseynield"
name                     : &name "Lindsey Nield"
description              : &description "my personal website"
url                      : https://lindseynield.github.io 
baseurl                  : ""
repository               : "lindseynield/lindseynield.github.io"

# User settings
username: "lindseynield"
greeting: "Hi, I'm Lindsey 👋"
user_title: Machine Learning & Data Engineer 
email: lindsey.g.nield@gmail.com
github_username:  lindseynield
linkedin_username: lindseynield
researchgate_profile: "Lindsey-Nield"

# Google-analytics
google-analytics:
  id: ""

markdown: kramdown